### ISSUE TITLE
Bugfix (major) : Users without admin privileges are still able to access Admin dashboard

### ISSUE THREAD

**Issue by EstelleMyddleware** [EstelleMyddleware/p5-blog-php#34]
Following up on this : https://github.com/EstelleMyddleware/p5-blog-php/issues/30
THis needs to be fixed ASAP.

**Comment by aurelienk** [comment]
Constructors should never return values (However they can throw domain specifics exceptions)

To solve the issue, you can:
- Move the code from the constructor to each method
- Throw an exception (ex: ROLE_ADMIN_REQUIRED)
- Create a Middleware

https://github.com/EstelleMyddleware/p5-blog-php/blob/a487ec50b3a192dacc1368945e70f4d35bd74648/public_html/src/Controller/AdminController.php#L77-L80
